"""Add position field to Board model

Revision ID: 1efd9303c3c5
Revises: 2859f7ddf76e
Create Date: 2025-04-23 09:00:58.736104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efd9303c3c5'
down_revision = '2859f7ddf76e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
