"""Add board member permissions

Revision ID: e8e6f25c934b
Revises: a9389a4b2009
Create Date: 2025-04-28 20:41:20.034704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e6f25c934b'
down_revision = 'a9389a4b2009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission', sa.Enum('VIEW', 'EDIT', 'MANAGE', name='boardpermission'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_members', schema=None) as batch_op:
        batch_op.drop_column('permission')

    # ### end Alembic commands ###
